### PR TITLE
add a jar for the checkAlignmentQuality command line program

### PR DESCRIPTION
**Pull request by geoffjentry**

### CODE REVIEW

**Comment by mcovarr** [comment]
Should we have one `janky-apollo-clps.jar` to hold these sorts of things, or do you think will this be the only one of its kind?

**Comment by geoffjentry** [comment]
We can worry about that when N > 1 (although I doubt that'll happen)

**Comment by mcovarr** [comment]
:+1: (assuming the jars are filled purely with awesomeness)

**Comment by geoffjentry** [comment]
If by awesomeness you mean trojans and logic bombs, yes.

**Comment by mcovarr** [comment]
In hindsight I probably should have been more specific.

**Pull request merged**
